#!/usr/bin/python3

import xmltodict
import random

class Player:
	def __init__ (self, name="", health=100, strength=10, level=1, xp=0):
		self.name = name
		self.health = health
		self.strength  = strength
		self.level = level
		self.xp = xp
		
		xml_file = open("levels.xml", "r")
		levels = xmltodict.parse(xml_file.read())
		xml_file.close()
		
		tmp=levels["levels"]["level"]
		
		
		self.levels={}

		for level in tmp:
			self.levels[ int( level["@num"]) ] = int(level["@xp"])
	
		print(self.levels)
	def set_health (self, health):
		self.health=health
	def set_strength (self, strength):
		self.strength=str(strength)
	def set_level (self, level):
		self.level=level
	def get_level (self, xp=-1):
		if xp==-1:
			return self.level

		level_cur =self.level
		for level in self.levels:
			if self.levels[level] <= xp:
				level_cur = level
		return level_cur

	def set_xp (self, xp):
		self.xp=xp
	
	def hurt (self, damage):
		
		if health >=0:
			health-=damage
			return false
		if health <=0:
			return true

	def attack (self):
		return random.randint(0,self.strength)
	
	def show_info (self):
		print("Name: "+(self.name))
		print("Health: "+str(self.health))
		print("Strength: "+str(self.strength))
		print("Level: "+str(self.level))
		print("XP: "+str(self.xp))
			
	def input_info(self):
		self.name=int(input("Dime tu nombre: "))
		self.health=int(input("Dime tu vida: "))
		self.strength=int(input("Dime fuerza: "))
		self.level=int(input("Dime tu nivel: "))
		self.xp=int(input("Dime tu cantidad de experiencia: "))
		
		return{
		"name": self.name,
		"health": self.health,
		"strength": self.strength,
		"level": self.level,
		"xp": self.xp
		}


	def write_info(self, export):
		player_xml = xmltodict.unparse(export, pretty=True)
		print(player_xml)
		f = open("player_xml", "w")
		f.write(player_xml)

		f.close()
	
	def read_info (self):
		xml_file=open("player_xml", "r")
		player_tmp=xmltodict.parse(xml_file.read())
		info=player_tmp["player_save"]["player"]
		self.name = info["name"]
		self.health = int(info["health"])
		self.strength = info["strength"]
		self.level = info["level"]
		self.xp = info["xp"]

def show_info (self):
		print("Name: " + str(self.name))
		print("Health: " + str(self.health))
		print("Strength: " + str(self.strength))
		print("Level: " + str(self.level))
		print("XP:" + str(self.xp))
		

if __name__ == "__main__":
	player = Player("Juan Ramon")
	
	print(player.get_level(100))
